#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OLLAMA_SYSTEM Setup Complete - Summary
Shows what was created and how to use it
"""

from pathlib import Path

OLLAMA_SYSTEM = Path(r'E:\AI_Tools\Central_Repository\OLLAMA_SYSTEM')

print("=" * 70)
print("OLLAMA_SYSTEM SETUP COMPLETE")
print("=" * 70)
print()
print("Directory Structure Created:")
print("-" * 70)
for item in sorted(OLLAMA_SYSTEM.rglob('*')):
    if item.is_file():
        rel_path = item.relative_to(OLLAMA_SYSTEM)
        print(f"   {rel_path}")
print()
print("=" * 70)
print("KEY FILES")
print("=" * 70)
print()
print("Configuration:")
print(f"   {OLLAMA_SYSTEM / 'config' / 'ollama_config.json'}")
print()
print("Python Manager:")
print(f"   {OLLAMA_SYSTEM / 'scripts' / 'ollama_manager.py'}")
print()
print("Startup Script:")
print(f"   {OLLAMA_SYSTEM / 'batch_files' / 'start_ollama_gpu.ps1'}")
print()
print("Documentation:")
print(f"   {OLLAMA_SYSTEM / 'README.md'}")
print(f"   {OLLAMA_SYSTEM / 'docs' / 'OLLAMA_SYSTEM_GUIDE.md'}")
print()
print("=" * 70)
print("USAGE FROM ANY WORKSPACE")
print("=" * 70)
print()
print("```python")
print("import sys")
print("from pathlib import Path")
print()
print("# Add Central Repository to path")
print("CENTRAL_REPO = Path(r'E:\\AI_Tools\\Central_Repository')")
print("sys.path.insert(0, str(CENTRAL_REPO))")
print()
print("# Import Ollama System")
print("from OLLAMA_SYSTEM.scripts.ollama_manager import get_ollama_system")
print()
print("# Use it")
print("ollama = get_ollama_system()")
print("if not ollama.is_running():")
print("    ollama.start_server()")
print("result = ollama.query('codellama:70b', 'Your prompt')")
print("```")
print()
print("=" * 70)
print("INTEGRATION STATUS")
print("=" * 70)
print()
print(" United Nations System - Integrated")
print("   - Uses centralized Ollama System")
print("   - Sherlock Holmes/Tony Stark  codellama:70b")
print("   - Judge  codellama:70b")
print()
print("=" * 70)
print("NEXT STEPS")
print("=" * 70)
print()
print("1. Start Ollama:")
print("   powershell -File \"E:\\AI_Tools\\Central_Repository\\OLLAMA_SYSTEM\\batch_files\\start_ollama_gpu.ps1\"")
print()
print("2. Download codellama:70b:")
print("   ollama pull codellama:70b")
print()
print("3. Test the system:")
print("   python E:\\AI_Tools\\Central_Repository\\OLLAMA_SYSTEM\\scripts\\test_ollama_system.py")
print()
print("=" * 70)

